### ISSUE TITLE
Ecarts entre les données de La Poste et la BAN

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/donnees-initiales#12]
Issu notamment de https://github.com/BaseAdresseNationale/api-gestion/issues/175 et https://github.com/BaseAdresseNationale/api-gestion/issues/210 et https://github.com/BaseAdresseNationale/api-gestion/issues/154.

A réactualiser avec l'init du 30/06/2017

**Comment by odorie** [comment]
@clodio, pouvez-vous aussi mettre à jour ce ticket et en faire des tickets unitaires

**Comment by clodio** [comment]
nous ne sommes plus en capacité de faire les mêmes tests que ceux qu'avait réalisé Christophe Prudent, nous avons mis en oeuvre d'autres test basé sur les fichiers hexa.
