### ISSUE TITLE
Gérer les fusions de communes

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/donnees-initiales#14]
Actuellement de nombreux groupes ne sont pas chargés à l'init de la BAN car ils ne font pas référence à des communes du COG 2017 : en effet les données du fantoir, de l'IGN et de la poste ne sont pas forcément à jour des fusions de commune 2017 et/ou les codes fantoirs ne sont pas à jour.

Issu de https://github.com/BaseAdresseNationale/api-gestion/issues/182

Mettre les anciens noms de communes en groupes secondaires

**Comment by parville** [comment]
Il faudrait résoudre ceci rapidement car les fusions de communes sont un vrai sujet d'adresse. Et là on ne peut pas avancer sur ce sujet.

**Comment by odorie** [comment]
Ce développement est en cours de recette interne équipe projet. Si c'est bon, vous verrez le résultat lors du prochain test d'initialisation et nous vous solliciterons pour le recetter.

**Comment by ebuard** [comment]
A recetter.

**Comment by odorie** [comment]
Les données de fin d'année se chargent mieux: la plupart des fusions ont été intégrées dans les différentes sources.
Lors de l'init, nous redirigeons les codes postaux et les groupes de des différentes sources vers les bons codes insee s'ils pointaient vers un ancien code insee. Cela permet de les charger lors de l'init.
TODO:
- faire la redirection pour les hn
- éventuellement mettre en groupes secondaires les anciens nom de commune

**Comment by odorie** [comment]
Pas besoin de faire la redirection pour les hn car hn chargés avec le lien vers les voies.
Pour les groupes secondaires, à mettre en place éventuellement en post-init.
