### ISSUE TITLE
Mauvais remplissage du champ positioning de Position

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/donnees-initiales#15]
Ce champ est toujours rempli à other dans la BAN alors que le json importé contient d'autres valeurs

**Comment by ebuard** [comment]
Correction de la commande d'import de json de l'API

**Comment by odorie** [comment]
Je rouvre ce ticket: tous les positioning sont toujours à other ...

**Comment by odorie** [comment]
Commande d'init de l'API corrigé
