### ISSUE TITLE
Diminuer le nombre de messages d'erreurs/warnings

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/donnees-initiales#25]
Actuellement on a un nombre important de messages d'erreurs/warnings à l'import notamment car les fusions de communes 2017 ne sont pas prises en compte dans le code d'init. Mais il faut vérifier que ces messages que les fusions et corriger les cas restants (ou en tout cas les analyser ...).

Pour info, sur le 33, on a : 
- 2 erreurs sur les post codes
- 43 erreurs sur les groupes
- 1874 erreurs sur les hn
- 1203  erreurs sur les positions

**Comment by gschittek** [comment]
Apres verification suite aux appariements de group on a sur le 33
5 erreurs sur les groupes (correspondant aux anciennes communes apres fusion)
25 erreurs sur les housenumbers (postcodes non trouvés)
1580 erreurs sur les housenumbers
617 erreurs sur les positions

**Comment by gschittek** [comment]
Apres modification du script d'init et de l'API, on obtient sur le 33 : 
5 erreurs sur les groups
458 erreurs sur les housenumbers (dus a des doublons dans les données IGN et/ou La Poste)
11 erreurs sur les positions (dus aux erreurs des housenumbers)

**Comment by odorie** [comment]
Plus d'erreurs à l'import du 33, 90

**Comment by odorie** [comment]
Encore 5 erreurs sur les groupes du 01 qui ne sont pas importés et du coup celà entraine le non import de quelques hn et positions

**Comment by odorie** [comment]
Après filtrage des groupes ign sans nom et des hn et positions liés, il reste 1 erreur sur le département 01 sur le groupe 01001A030

**Comment by odorie** [comment]
Le nombre d'erreurs a largement diminué. je ferme le ticket. 
On ouvrira des tickets spécifiques pour chaque type d'erreurs restantes
