### ISSUE TITLE
Choix des noms de groupes retenus à l'issue de l'init

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/donnees-initiales#3]
Actuellement le nom retenu est le nom DGFIP/BANO (donc minuscules accentuées capitalisées) quand il existe, autrement le nom fantoir, autrement le nom IGN, autrement le nom La Poste (dans cet ordre).

Cet ordre est-il judicieux ? Pas forcément d'après le ticket https://github.com/BaseAdresseNationale/api-gestion/issues/214.

cquest proposait : 
- Le libellé officiel est celui de la commune et doit l'emporter en règle générale, sauf erreur (qui devrait être exceptionnelle, mais il y en a aussi).
- ensuite, par expérience, le libellé de La Poste semble très fiable.
- ensuite, vient celui de l'IGN (sans traitement automatique)
- et pour terminer celui de FANTOIR.

De plus il était proposé d'utiliser les noms DGFIP/BANO uniquement si ceux-ci étaient égaux aux autres libellés après normalisation.

**Comment by ebuard** [comment]
Si les noms sont différents après normalisation, ajouter un warning dans Attributes avec le nom de l'autre source.

**Comment by odorie** [comment]
Suite aux journées de travail sur l'initialisation de décembre/janvier, on est parti pour retenir les noms dans l'ordre suivant de priorité décroissante :
- le nom issu du cadastre (si il est identique au dernier nom retenu La Poste/IGN/Fantoir  (après passage en majuscules désaccentuées et autres -> à préciser))  
- le nom de La Poste
- le nom IGN repassé en majuscules accentuées
- le nom fantoir

**Comment by odorie** [comment]
Fait
