### ISSUE TITLE
Vérifier l'export des voies IGN pour les indices de positionnement 6

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/donnees-initiales#30]
Ne pas prendre en compte le nom de l'objet support en cas d'indice de positionnement 6, mais le nom de la voie SGA et son id_pseudo_fpb

**Comment by ebuard** [comment]
OK.
Pas de position, 1 HN et 1 group avec  nom de la voie  et  id_pseudo_fpb

**Comment by ebuard** [comment]
A faire: 
- Rajouter dans le script d'init la suppression des positions si indice_de_positionnement = 6 (cas ADRNIVX_0000000287358775 qui crée une position)

**Comment by odorie** [comment]
Nouveau ticket ouvert #63 pour la suppression des positions d'indice de positionnement 6.
Dans ce ticket, traiter uniquement l'export de la voie

**Comment by odorie** [comment]
Le programme d'export des adresses IGN lie bien l'adresse IGN à la voie SGA par le champ id_pseudo_fpb contenu dans l'adresse SGA (sous partie du champ identifiant_adresse_sga) (quelque soit l'indice de positionnement). Le lien vers objet support n'est pas utilisé.

Le nom de la voie exporté est celui de la voie SGA, mis en minuscule si elle correspond à une voie BDUni (lien par fait par l'id_pseudo_fpb)
