### ISSUE TITLE
Hn avec numéro null

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/donnees-initiales#31]
Actuellement, la base contient des hn avec numéro null pour stocker le code voie de LP. De plus en cas de voie pluridistribuée, il y a plusieurs numéros null: 1 pour chaque code postal.
Ces numéros null perturbent les utilisateurs. Il faudra bien documenter la base, voire ne pas les conserver et les exporter.

Dans le cas où il sera décidé de ne pas mettre les identifiants de La Poste dans la base, il faudra supprimer certains hn null, sauf ceux des voies pluridistribuées.

**Comment by odorie** [comment]
A attente de décision sur la présence d'identifiant poste dans la BAN

**Comment by odorie** [comment]
La décision de garder les identifiants Poste a été prise. On peut fermer ce ticket.
