### ISSUE TITLE
Améliorer la table des libellés courts de groupes

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/donnees-initiales#33]
Cette table sert à rapprocher les noms de groupes.

Suite à la journée de travail sur l'init du 17/01, les actions suivantes ont été proposées :

- tantièmes : 1 ER(E) -> 1E, 19( )EM(E) -> 19E ...
- les chiffres romains: II -> 2 ... (attention aux I, V, VI et X). Monter jusqu'à XXIII
- R I -> RI
- Compléter le travail sur les DIT/DITE
- en avant dernier: 1E -> PREMIER, 2E -> DEUXIEME ...
- à la fin rebasculer: 1 -> UN, 2 -> DEUX, .. 20 -> VINGT, 30 -> TRENTE
- les dates 11 novembre 1918, 14 juillet ... Pas toujours normalisées de la même façon
- QUATRES -> QUATRE, CENTS -> CENT ??
- ... à compléter surement en regardant les données

**Comment by jdesboeufs** [comment]
Ce serait pas mal de faire un fichier CSV réutilisable pour ce cas de figure.
On pourrait s'en servir dans les géocodeurs.

**Comment by odorie** [comment]
Fait en partie.

Il reste cependant des points à améliorer:
- QUATRES -> QUATRE, CENTS -> CENT 
- à la fin rebasculer: 1 -> UN, 2 -> DEUX, .. 20 -> VINGT, 30 -> TRENTE
- tantièmes en texte
- les dates

Et surement d'autres

**Comment by odorie** [comment]
Pas fait entièrement
