### ISSUE TITLE
Adresses issues du cadastre

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/donnees-initiales#39]
Mise à disposition des Adresses issues du cadastre en remplacement des données DGFiP/BANO.

**Comment by odorie** [comment]
Import du 90 lors de l'atelier du 9/03 (Jérôme et Olivier).
Ajout du code postal dans l'export qui sert ensuite à compléter la BAN.
Ajout de la destination (issu de majic) dans l'export puis dans le champ attributes des hns (cela servira notamment pour qualifier les 5000).

**Comment by odorie** [comment]
TODO:
- tester France entière
- on a observé une diminution du nombre de noms de voies issus du plan cadastral par rapport à l'export dgfip-bano (sur le 90, on passe de 2700 à 2390). Continuer à analyser les différences comme vendredi pour voir si on ne peut pas en ramener encore un peu
- B-> BIS ...

**Comment by odorie** [comment]
Quelques petits retours sur le chargement France entière des voies cadastre.

1- On passe de 1 096 000 avec dgfip-bano à 937 000 voies cadastre. Comme vendredi, voici quelques voies qui étaient présentes avant et qui ne le sont plus:
 90003     | Rue de Bourg Sous Chatelet   | 900030005
 90003     | Rue Raymond Burais           | 900030006
 90003     | Rue de la Charmotte          | 900030008
 90003     | Impasse des Fleurs           | 900030017
 90003     | Rue Novier                   | 900030027
 90003     | Rue de la Plaine             | 900030030
 90003     | Allée de l'Écluse            | 900030031
 90003     | Impasse de la Rochette       | 900030037
 90003     | Rue du Stade                 | 900030041
 90004     | Rue des Bouleaux             | 900040002
 90004     | Rue Vie de la Croze          | 900040004
 90004     | Rue des Chènes               | 900040006
 90004     | Rue des Merisiers            | 900040010
 90004     | Rue des Marronniers          | 900040012
 90004     | Impasse des Sapins           | 900040018
 90004     | Impasse des Tombois          | 900040019
 90004     | Rue des Tilleuls             | 900040021
 90004     | Rue des Alisiers             | 900040022
 90004     | Rue des Courbes Fauchées     | 900040023
 90004     | Rue des Roseaux              | 900040024

2 - accentuation différente de dgfip-bano, est-ce normal:
90003     | Rue d'Étueffont              | 900030009  |Rue d'Etueffont
 90004     | Rue Sur La Côte              | 900040005  |Rue Sur la Cote

3- Quelques noms bizarres ou en majuscules, est-ce normal:
  90004 | 900040015 | Iinpasse des Prés
  90010 | 900100431 | Place Janine BAZIN
  90010 | 900100434 | Rue Alphonse BEAU DE ROCHAS
  90010 | 900100510 | RUE de Bordeaux
  90010 | 900100662 | Rue de BERLIN
  90010 | 900100683 | rue de la cavalerie la la
  90010 | 900100978 | Place commune de 1871 PARIS de la
  90010 | 900101790 | Avenue du GÚnÚral Sarrail
  90010 | 900102700 | PLACE MARTIN LUTHER KING
  90010 | 900102890 | impasse l'observatoire de
  90010 | 900103220 | Rue du Président Roosevelt de

**Comment by jdesboeufs** [comment]
Je regarde ça. Probablement des ajustements à faire.

**Comment by jdesboeufs** [comment]
J'ai déjà identifié plusieurs choses.

Certains libellés se trouvent dans la couche des tronçons routiers, d'autres dans les éléments ponctuels (lotissements).

Voici l'exemple d'un tronçon carrefour, qui mixe deux voies :
<img width="649" alt="capture d ecran 2018-03-14 a 23 09 38" src="https://user-images.githubusercontent.com/1231232/37478757-66994cbc-287b-11e8-95c9-9ebdad05e9ec.png">

Concernant la divergence avec DGFiP/BANO, dans certains cas c'est le plan qui a changé, mais aussi parce que l'algorithme utilisé est différent. Ils partent de FANTOIR et réaccentuent mot à mot, alors que l'approche "Etalab" est de tenter de reprendre la chaîne complète, potentiellement plus riche que le libellé FANTOIR, mais aussi plus sujette aux déchets.
Je regarde pour ajuste le scoring de manière à filtrer un maximum de déchets, et je vais implémenter la startégie BANO en complément, lorsque la stratégie 1 ne donne pas satisfaction.

Je t'envoie un nouveau fichier avant demain soir.

**Comment by jdesboeufs** [comment]
Bon j'ai bien avancé mais j'ai envie de tester de nouvelles choses.
Je te suggère de jeter un oeil aux HN en attendant, car finalement les libellés c'est une question de réglages.

**Comment by odorie** [comment]
Sur les HNs on avait déjà regardé vendredi dernier. j'ai recommencer avec le nouvel export. Sur le 90, l'export dgfip etalab contient 42540 hn. 40 237 sont rapprochés avec les hn de l'IGN. C'est un bon chiffre !
Sur les 2200 non rapprochés: il y a encore des soucis sur les B/BIS, T/TER (1000  cas environ), des 5000/9000 (400 cas) et environ 700 autres cas (voies non appariées et hn détruites par le collecteur IGN).

Je vais travailler de mon côté sur les B/BIS IGN: il y a encore du ménage à faire.

Je dois encore jeter un coup d'oeil aux coordonnées dgfip/etalab

**Comment by jdesboeufs** [comment]
J'ai déposé une nouvelle version du fichier, estampillée `v12`, qui correspond à la version `v0.3.0-12` du [script de production des données](https://github.com/etalab/adresses-cadastre).

Depuis la `v9`, les changements sont les suivants :

- amélioration systématique des libellés via un nettoyage de la ponctuation et application d'un algorithme de capitalisation sommaire ;
- accentuation des mots FANTOIR grâce à un corpus de mots formés à partir des libellés du PCI Vecteur d'une même commune.

Le champ `libelle_voie_type` indique désormais la source de construction des mots, mais plus l'état de la casse et de l'accentuation.

**Comment by odorie** [comment]
Je vais le recharger.
En attendant j'ai comparé les x,y sur l'ancienne version. j'ai un peu plus d'éloignement avec les données IGN. Peut-être parce que l'on a plus de hn appariés ( 4000 en plus dans dgfip etalab) ?

Sur le dep 90, pour le hn dgfip/bano et ign appariés (36 000) :
- 42 positions > 500 m
- 327 positions entre 100 et 500 m
- 475 positions entre 50 et 100 m

Avec dgfip/etalab et ign (40 000 appariements):
- 80 (25 sans les hn 5000 ...) positions > 500 m
- 780 (546 sans les hn 5000 ...) positions entre 100 et 500 m
- 1318 (1071 sans les hn 5000 ...) positions entre 50 et 100 m

**Comment by odorie** [comment]
Sur les 25 positions ( hn != 5000) > 500 m, 12 seulement sont entrance.
Sur les 546 positions ( hn != 5000) entre 100 et 500 m, 197 entrance.

Je viens d'importer le nouveau fichier (938 000 voies "plan cadastral"), environ comme le précédent.

L'appariement des hns avec l'IGN donnent de meilleur résultat (notamment car nous avons traité les B-> BIS ...: il ne reste plus que 1530 hn dgfip etalab qui ne matchent pas avec les hn IGN (avant c'était 2200)
