### ISSUE TITLE
Dans la base du 33, il manque des codes postaux

### ISSUE THREAD

**Issue by clodio** [BaseAdresseNationale/donnees-initiales#42]
## Contexte

Utilisation des données ban 33 avec cea du 15 janvier 2018

Chargement d'une table ran_postcode transformé en ran_postcode pour l'initialisation à partir des fichier d'adresse de La Poste, suppression de cette table des données non rattachées au 33.
`  DELETE FROM ran_postcode WHERE co_postal not like '33%';`

## Action
1- Recherche des différences entre les données postcode et le référentiel Poste
`SELECT ran_postcode.co_postal, ran_postcode.lb_l6 FROM ran_postcode  `
 `EXCEPT  `
 `SELECT postcode.code, postcode.name FROM postcode  `

2- Recherche par le nom d'un ville identifiée comme manquante
`SELECT * FROM municipality WHERE name like '%FOUGUEYROLLES%' `

## Résultat obtenu

1- des éléments sont retournés

| co_postal | lb_l6 |
| -- | -- |
| 33220 | FOUGUEYROLLES |
| 33220 | PORT STE FOY ET PONCHAPT |

2- Aucun résultat

## Résultat attendu

Présence de tous les codes postaux dans la table postcode 
Présence de toutes les municipalités dans la table municipality 

1- aucune valeur remontée -> tous les codes postaux de la poste doivent être dans la base

2 - la ville recherchée doit être présente

**Comment by clodio** [comment]
le problème vient probablement que l'export par département se base sur les code insee et certains débuts de codes postaux ne correspondent pas aux code insee. Par exemple Fougueyrolles à le code insee 24189

**Comment by odorie** [comment]
Le souci est-il encore présent sur la base France entière livrée ce jour ?

**Comment by clodio** [comment]
#dump022018: Résolu
