### ISSUE TITLE
Dans la base du 33, il n'y a pas le même nombre d'éléments group entre les données poste et la ban

### ISSUE THREAD

**Issue by clodio** [BaseAdresseNationale/donnees-initiales#45]
## Contexte

Utilisation des données ban 33 avec cea du 15 janvier 2018

## Action
Récupérer les données source laposte de type group qui ne sont pas présente dans la table group
`SELECT * `
`FROM ran_group LEFT JOIN "public"."group" g  ON ran_group.co_voie=g.laposte`
`WHERE g.laposte IS NULL;`

## Résultat obtenu

143 éléments ne sont pas présents

## Résultat attendu

Tous les éléments sont présents

## Autre question/réflexion pour la poste 

group.laposte est un co_voie et pas un cea : n'est-ce pas un problème? `

**Comment by odorie** [comment]
Nous avions compris qu'il fallait mettre le co_voie dans l'idposte des groupes.
Et le cea dans des housemnumbers sans numéro (hn null) associés à ce groupe.
Au passage on a donc un co_voie pour un group ban alors que l'on peut avoir n cea pour un groupe ban.
Celà convient-il ?

**Comment by odorie** [comment]
Petite question: on a donc possiblement plusieurs fois le n cea identique en cas de voies multi-cp.
Donc dans la BAN, n fois le même identifiant la poste sur n hn nul pointant sur n postcode différents.

Exemple sur 2 voies LP:
 co_insee | co_voie  |    cea     | co_postal |        lb_voie
----------+----------+------------+-----------+-----------------------
 01104    | 00004147 | 0110422223 | 01410     | MENTHIERES
 01104    | 00004147 | 0110422223 | 01200     | MENTHIERES

**Comment by clodio** [comment]
la modélisation est ok

**Comment by clodio** [comment]
Le problème vient du filtre sur le 33 lors de l'export, les données qui ne sont pas présentes correspondent à des codes insee 24* avec un code_postal en 33*

La nouvelle requête ne remonte plus de problème
`SELECT *
FROM ran_group rg LEFT JOIN "public"."group" g ON rg.co_voie=g.laposte
WHERE g.laposte IS NULL and rg.co_insee like '33%';`

cf. issue #42

**Comment by clodio** [comment]
#dump022018: testé ok sur france entière (excepté codes postaux en 98+)
