### ISSUE TITLE
retours sur écarts BAN/RAN au 30/6/2017 (départements 06 et 90)

### ISSUE THREAD

**Issue by gschittek** [BaseAdresseNationale/donnees-initiales#46]
cf https://github.com/BaseAdresseNationale/api-gestion/issues/335

**Comment by odorie** [comment]
@clodio : ce ticket est-il toujours d'actualité ?

N'est -il pas repris dans d'autres tickets déjà ouverts ?

Sinon pouvez-vous le transformer en n tickets : 1 pour chaque problème remonté ?

**Comment by clodio** [comment]
voir commentaire dans le ticket BaseAdresseNationale/api-gestion#335
