### ISSUE TITLE
Choisir la date d'actualité des données utilisées lors de l'initialisation BAN finale

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/donnees-initiales#59]
Lors de l'atelier pilote de février 2017, les données suivantes ont été utilisées:
- COG (INSEE 2017)
- FANTOIR (DGFiP oct 2017)
- DGFiP/BANO (nov 2016)
- La Poste (fichier hexavia/hexacle sept 2017)
- IGN (décembre 2017)

Quelles données utiliser pour l'initialisation finale du mois d'avril ?

Il faudrait faire le test au plus tôt avec ces données pour identifier rapidement les problèmes de compatibilité bloquant (prise en compte des fusions de communes dans une des sources et pas dans l'autre ...)

**Comment by odorie** [comment]
En 2017 et début 2018, pour l'instant environ 40 fusions de communes (pour 100 anciennes communes).
Les fusions apparaissent dans les données IGN de prod et La Poste au fil de l'eau (peu de temps après la parution au JO)
Le COG sort entre mi-mars et mi-avril.
Le nouveau Fantoir est sorti en janvier

Pour l'init du 15/04, il faudra lancer le chargement vraisemblablement vers mi-mars et on ne pourra pas attendre le nouveau COG.

Proposition:
- COG 2017
- **FANTOIR janvier 2018 ou octobre 2017 ????** 
- DGFIP généré sur Fantoir octobre 2017, MAJIC mai 2017
- IGN mars 2018 généré sur Fantoir octobre 2017
- Hexavia/hexacle mars 2018

Remarque : à l'issue de l'init, les voies des 40 nouvelles fusions de commune seront chargées mais redirigées vers les anciennes communes (on sera conforme au  FANTOIR et au COG 2017) pour les voies appariées au FANTOIR. Les fusions de commune réalisées au fil de l'eau par l'IGN et La Poste seront donc détricotées.

**Comment by jdesboeufs** [comment]
FANTOIR étant un fichier historisé, et même s'il y a des cas aux marges, on peut prendre la version de janvier 2018.
Pour les Adresses du cadastre je lance une extraction globale demain matin avec MAJIC 2017, COG 2017, dernier FANTOIR (janvier 2018) et PCI d'octobre 2017.

La BAN étant une base de données du SPD, il est de bon ton d'utiliser le COG comme référence.
On pourra toujours râler ensuite pour accélérer sa parution.

**Comment by odorie** [comment]
Prendre le fantoir 2018
